publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
  - 'case-police'
allowBuilds:
  puppeteer: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@kitschpatrol/*'
